{application,mishka_chelekom,
             [{modules,['Elixir.MishkaChelekom',
                        'Elixir.MishkaChelekom.Application',
                        'Elixir.Mix.Tasks.Mishka.Ui.Add',
                        'Elixir.Mix.Tasks.Mishka.Ui.Add.Files',
                        'Elixir.Mix.Tasks.Mishka.Ui.Add.Files.Args',
                        'Elixir.Mix.Tasks.Mishka.Ui.Export',
                        'Elixir.Mix.Tasks.Mishka.Ui.Gen.Component',
                        'Elixir.Mix.Tasks.Mishka.Ui.Gen.Components',
                        'Elixir.Mix.Tasks.MishkaChelekom.Install',
                        'Elixir.Mix.Tasks.MishkaChelekom.Install.Docs']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,igniter,
                             guarded_struct,igniter_js,owl]},
              {description,"Mishka Chelekom is a fully featured components and UI kit library for Phoenix & Phoenix LiveView"},
              {registered,[]},
              {vsn,"0.0.4"},
              {mod,{'Elixir.MishkaChelekom.Application',[]}}]}.
