{application,igniter_js,
    [{modules,
         ['Elixir.IgniterJs','Elixir.IgniterJs.Application',
          'Elixir.IgniterJs.Helpers','Elixir.IgniterJs.Native',
          'Elixir.IgniterJs.Parsers.CSS.Formatter',
          'Elixir.IgniterJs.Parsers.Javascript.Formatter',
          'Elixir.IgniterJs.Parsers.Javascript.Parser']},
     {compile_env,
         [{rustler_precompiled,[force_build,igniter_js],error},
          {rustler_precompiled,[force_build_all],error}]},
     {optional_applications,[rustler]},
     {applications,
         [kernel,stdlib,elixir,logger,rustler,jason,rustler_precompiled]},
     {description,
         "Javascript codemods, powered by a high-performance Rust parser integrated via NIFs\n"},
     {registered,[]},
     {vsn,"0.4.6"},
     {mod,{'Elixir.IgniterJs.Application',[]}}]}.
